[package]
name = "ratatable"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "=3.19.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
rat-ftable = "1.3.0"
ratatui = "0.29.0"
wraptatui = { path = "../wraptatui" }
